### ISSUE TITLE
 Problema para instalarlo en Kodi - leia

### ISSUE THREAD

**Issue by horusint** [arsat/contar-kodi#1]
Estimados, me encuentro con problemas para instalar el plugin en Kodi 18 (leia)  (Raspberry 3 - Libreelec)
bajé el contenido como ZIP pero entiendo  me debe estar faltando algo, o no es compatible con esta versión, agradezco la ayuda posible. Gracias.

**Comment by enderf** [comment]
Hola, esta es una versión preliminar desarrollada en Python 3 para Matrix. Todavía no está publicada en el repo oficial. Por el momento no tenemos pensado hacer un backport a Leia (Python 2) pero no debería ser muy complicado adaptarla. 
La única versión que tenemos publicada en el repo oficial es el plugin de Cine.ar Play, también para Matrix.
Saludos

**Comment by horusint** [comment]
Gracias, si ahi me di cuenta lo que mencionas, muchas gracias, voy a ver si se puede hacer ese backport, muchas gracias
